# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EditText.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TextRedactor(object):
    def setupUi(self, TextRedactor):
        TextRedactor.setObjectName("TextRedactor")
        TextRedactor.resize(540, 360)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TextRedactor.sizePolicy().hasHeightForWidth())
        TextRedactor.setSizePolicy(sizePolicy)
        TextRedactor.setMinimumSize(QtCore.QSize(540, 360))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/WindowPy/image/Twilight_Sparkle_Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TextRedactor.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(TextRedactor)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        TextRedactor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TextRedactor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        TextRedactor.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(TextRedactor)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(TextRedactor)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(TextRedactor)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(TextRedactor)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtWidgets.QAction(TextRedactor)
        self.actionExit.setObjectName("actionExit")
        self.actionCut = QtWidgets.QAction(TextRedactor)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(TextRedactor)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(TextRedactor)
        self.actionPaste.setObjectName("actionPaste")
        self.actionInfoProgramm = QtWidgets.QAction(TextRedactor)
        self.actionInfoProgramm.setObjectName("actionInfoProgramm")
        self.actionQt = QtWidgets.QAction(TextRedactor)
        self.actionQt.setObjectName("actionQt")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuHelp.addAction(self.actionInfoProgramm)
        self.menuHelp.addAction(self.actionQt)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(TextRedactor)

        QtCore.QMetaObject.connectSlotsByName(TextRedactor)

    def retranslateUi(self, TextRedactor):
        _translate = QtCore.QCoreApplication.translate
        TextRedactor.setWindowTitle(_translate("TextRedactor", "Редактор Текста"))
        self.menuFile.setTitle(_translate("TextRedactor", "Файл"))
        self.menuEdit.setTitle(_translate("TextRedactor", "Правка"))
        self.menuHelp.setTitle(_translate("TextRedactor", "Помощь"))
        self.actionNew.setText(_translate("TextRedactor", "Новый"))
        self.actionOpen.setText(_translate("TextRedactor", "Открыть"))
        self.actionSave.setText(_translate("TextRedactor", "Сохранить"))
        self.actionSaveAs.setText(_translate("TextRedactor", "Сохранить как..."))
        self.actionExit.setText(_translate("TextRedactor", "Выход"))
        self.actionCut.setText(_translate("TextRedactor", "Вырезать"))
        self.actionCut.setShortcut('Ctrl+X')
        self.actionCopy.setText(_translate("TextRedactor", "Копировать"))
        self.actionCopy.setShortcut('Ctrl+C')
        self.actionPaste.setText(_translate("TextRedactor", "Вставить"))
        self.actionPaste.setShortcut('Ctrl+V')
        self.actionInfoProgramm.setText(_translate("TextRedactor", "О программе"))
        self.actionQt.setText(_translate("TextRedactor", "О Qt"))
